# Generated by Django 2.0.6 on 2018-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklocation',
            name='register_id',
            field=models.CharField(max_length=100, verbose_name='등록번호'),
        ),
    ]
