# Generated by Django 2.0.6 on 2018-06-19 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180618_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='book_id'),
        ),
    ]
